ALTER TABLE `SliderItem`
  ADD COLUMN `trPretitle` VARCHAR(255) NULL,
  ADD COLUMN `enPretitle` VARCHAR(255) NULL,
  ADD COLUMN `trBadge`    VARCHAR(255) NULL,
  ADD COLUMN `enBadge`    VARCHAR(255) NULL,
  ADD COLUMN `trBadgeSub` VARCHAR(255) NULL,
  ADD COLUMN `enBadgeSub` VARCHAR(255) NULL;
