CREATE TABLE `ServiceDetail` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `key` VARCHAR(60) NOT NULL,
    `locale` VARCHAR(8) NOT NULL,
    `slug` VARCHAR(120) NOT NULL,
    `label` VARCHAR(120) NOT NULL,
    `title` VARCHAR(255) NOT NULL,
    `intro` TEXT NOT NULL,
    `heroCta` VARCHAR(120) NOT NULL,
    `aboutTitle` VARCHAR(255) NOT NULL,
    `aboutLead` TEXT NOT NULL,
    `aboutBody` TEXT NOT NULL,
    `benefitsTitle` VARCHAR(255) NOT NULL,
    `benefits` JSON NOT NULL,
    `processTitle` VARCHAR(255) NOT NULL,
    `processSteps` JSON NOT NULL,
    `deliverablesTitle` VARCHAR(255) NOT NULL,
    `deliverables` JSON NOT NULL,
    `faqTitle` VARCHAR(255) NOT NULL,
    `faq` JSON NOT NULL,
    `ctaTitle` VARCHAR(255) NOT NULL,
    `ctaSubtitle` TEXT NOT NULL,
    `ctaButton` VARCHAR(120) NOT NULL,
    `image` VARCHAR(100) NOT NULL,
    `status` ENUM('DRAFT', 'PUBLISHED', 'ACTIVE') NOT NULL DEFAULT 'DRAFT',
    `publishedAt` DATETIME(3) NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    UNIQUE INDEX `ServiceDetail_key_locale_key`(`key`, `locale`),
    UNIQUE INDEX `ServiceDetail_slug_locale_key`(`slug`, `locale`),
    INDEX `ServiceDetail_locale_status_idx`(`locale`, `status`),
    INDEX `ServiceDetail_updatedAt_idx`(`updatedAt`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `CaseStudy` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `slug` VARCHAR(120) NOT NULL,
    `locale` VARCHAR(8) NOT NULL,
    `client` VARCHAR(190) NOT NULL,
    `sector` VARCHAR(120) NOT NULL,
    `duration` VARCHAR(80) NOT NULL,
    `year` VARCHAR(10) NULL,
    `image` VARCHAR(255) NOT NULL,
    `challenge` TEXT NOT NULL,
    `approach` TEXT NOT NULL,
    `result` TEXT NOT NULL,
    `scope` JSON NOT NULL,
    `services` JSON NULL,
    `metrics` JSON NOT NULL,
    `gallery` JSON NULL,
    `testimonial` JSON NULL,
    `status` ENUM('DRAFT', 'PUBLISHED', 'ACTIVE') NOT NULL DEFAULT 'DRAFT',
    `publishedAt` DATETIME(3) NULL,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,

    UNIQUE INDEX `CaseStudy_slug_locale_key`(`slug`, `locale`),
    INDEX `CaseStudy_locale_status_idx`(`locale`, `status`),
    INDEX `CaseStudy_updatedAt_idx`(`updatedAt`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
