export const trAdminDashboardContent = {
  title: "Hos Geldiniz, Nimedya",
  subtitle: "Bugun icin sitenizin genel performans ozeti asagidadir.",
  stats: {
    projects: "Toplam Proje",
    messages: "Bekleyen Mesajlar",
    posts: "Toplam Blog Yazisi",
    publishedHint: "Yayindaki bloklar",
    newMessageHint: "Yeni mesaj",
    mediaFilesHint: "Medya dosyasi",
  },
  actions: {
    addContent: "Yeni Icerik Ekle",
    editContent: "Icerik Duzenle",
    uploadMedia: "Medya Yukle",
    editSeo: "SEO Duzenle",
  },
  table: {
    sectionTitle: "Son Eklenen Icerikler",
    viewAll: "Tumunu Gor",
    colTitle: "Baslik",
    colType: "Tip",
    colDate: "Tarih",
    colStatus: "Durum",
  },
  statusLabels: {
    published: "Yayinda",
    draft: "Taslak",
    new: "Yeni",
    read: "Okundu",
    archived: "Arsiv",
  },
  quickActions: "Hizli Islem",
  systemStatus: "Sistem Durumu",
  system: {
    api: "API",
    database: "Veritabani",
    online: "Cevrimici",
    offline: "Cevrimdisi",
  },
};

export const trAdminSliderContent = {
  breadcrumbAdmin: "Admin",
  breadcrumbPage: "Slider Yonetimi",
  title: "Slider Yonetimi",
  subtitle: "Web sitenizin ana sayfa vitrini iceriklerini buradan yonetin.",
  addNew: "Yeni Ekle",
  activeSliders: "Aktif Sliderlar",
  activeCount: "3 Aktif",
  formTitle: "TR / EN Icerik Girisi",
  formSubtitle: "TR alanlarini manuel girin, sonra AI ile EN alanlarini doldurun.",
  previewTitle: "Onizleme",
  translateButton: "AI ile Ingilizce Icerikleri Tamamla",
  translating: "Ceviriliyor...",
};
